# Deep Fund Configuration
exp_name: "deepseek-buffett"

# Trading settings
cashflow: 100000
tickers:
  - AAPL
  - AXP
  - BAC
  - KO
  - CVX

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - technical
  - insider
  - company_news
  - policy

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "DeepSeek" 
  model: "deepseek-chat" # DeepSeek V3