# Deep Fund Configuration
exp_name: "aihubmix-test"

# Trading settings
cashflow: 100000
tickers:
  - MSFT
  - NVDA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - company_news
  - insider

# AihubMIX is a unified API proxy for all LLM models
llm:
  provider: "AiHubMix" 
  model: "gpt-4.1-mini"

