# Deep Fund Configuration
exp_name: "anthropic-test"

# Trading settings
cashflow: 100000
tickers:
  - MSFT
  - NVDA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - fundamental
  - technical

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "Anthropic" 
  model: "claude-3-7-sonnet-20250219"

