# Deep Fund Configuration
exp_name: "firework-test"

# Trading settings
cashflow: 100000
tickers:
  - TSLA
  - NVDA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - company_news
  - technical


# Fireworks.ai is a unified API proxy for many LLM models
llm:
  provider: "Fireworks" 
  model: "accounts/fireworks/models/llama-v3p1-70b-instruct" 

