# Deep Fund Configuration
exp_name: "ollama-test"

# Trading settings
cashflow: 100000
tickers:
  - BABA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - fundamental

# Ollama is a community-driven LLM provider
# you should have a local ollama server running
llm:
  provider: "Ollama" 
  model: "llama3.1:latest" 

