# Deep Fund Configuration
exp_name: "openai-test"

# Trading settings
cashflow: 100000
tickers:
  - MSFT
  - NVDA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - fundamental
  - technical

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "OpenAI" 
  model: "gpt-4o-mini"

