# Deep Fund Configuration
exp_name: "qwen-test"

# Trading settings
cashflow: 100000
tickers:
  - AAPL
  - NVDA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - technical
  - company_news

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "Alibaba" 
  model: "qwen-max-2025-01-25"