# Deep Fund Configuration
exp_name: "zhipu-test"

# Trading settings
cashflow: 100000
tickers:
  - MSFT
  - NVDA
  - TSLA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - technical
  - company_news

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "ZhiPu" 
  model: "glm-4-air-250414"